name: Auto Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/cli-action@v1

      - name: Create Pull Request
        run: |
          gh auth login --with-token < ${{ secrets.AUTO_PR_TOKEN }}
          gh pr create --base main --head your-branch-name --title "Auto PR" --body "Automatically created pull request"
